alter table item drop foreign key FKhc10j8kpau312bmp2oa2k5tl7;
alter table item drop foreign key FKtpf6xe8gofj3yywatdw0l19un;
alter table item drop foreign key FKn4b0yw5earv5c0qww3s1ng8sb;
alter table item drop foreign key FKma002dx0ih3lmu46o58xufifo;
alter table item drop foreign key FK59l645fqxtw26ctcmdclg1rke;
alter table item_item_spells drop foreign key FKe6fyikrn30ty5vyll3evc54ys;
alter table item_item_spells drop foreign key FKprg6l7w00u2aohqxw4bekpfx9;
alter table item_set_effects drop foreign key FK9mjms4os2bw5v2junptrxkket;
drop table if exists item;
drop table if exists item_item_spells;
drop table if exists item_set_effects;
drop table if exists item_class;
drop table if exists item_media;
drop table if exists item_set;
drop table if exists item_spells;
drop table if exists item_stats;
drop table if exists item_subclass;
